### ISSUE TITLE
README should be updated

### ISSUE THREAD

**Issue by mattlorimor** [jamiecounsell/django-pwned-passwords#3]
The current README should be updated to reflect the fact that there are no rate-limiting worries since https://github.com/jamiecounsell/django-pwned-passwords/pull/1 has been merged.

> [There is no rate limit on the Pwned Passwords API.](https://haveibeenpwned.com/API/v2#RateLimiting)

**Comment by jamiecounsell** [comment]
Fixed in 3bc16f5
