### ISSUE TITLE
Password Pwn Count

### ISSUE THREAD

**Issue by slinkymanbyday** [jamiecounsell/django-pwned-passwords#5]
The Pwned Password API provided by Troy Hunt now provides how many breaches a password has been in.

Would be nice to have two things in regards to this:
1. Have a minimum breach setting. This would mean a password would have to be in X number of breaches before a validation error is thrown. Useful if you only want to protect against the most popular passwords.
2. Display how many breaches a password has been involved with in the error messages.

**Comment by jamiecounsell** [comment]
Available in 3.0! I'm not going to get into the process of showing how many breaches a password has been used in as that adds complexity around regionalization and is a bit outside the scope of this project.
