### ISSUE TITLE
not enough values to unpack in get_breach_count

### ISSUE THREAD

**Issue by pix106** [jamiecounsell/django-pwned-passwords#7]
* django-pwned-passwords version: 3.0.0
* Django version: 1.11.22
* Python version: 3.6
* Operating System: debian stable

### Description

as it is working fine now, i suppose the API was unavailable at the time this trace happenned :

```

...
File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/password_validation.py" in validate_password
  52.             validator.validate(password, user)

File "/usr/local/lib/python3.6/site-packages/django_pwned_passwords/password_validation.py" in validate
  35.         if not self.check_valid(password):

File "/usr/local/lib/python3.6/site-packages/django_pwned_passwords/password_validation.py" in check_valid
  57.             if self.get_breach_count(p_hash, response.text) >= self.min_breaches:

File "/usr/local/lib/python3.6/site-packages/django_pwned_passwords/password_validation.py" in get_breach_count
  87.             hash, count = line.split(":")

Exception Type: ValueError at /password_change_url/
Exception Value: not enough values to unpack (expected 2, got 1)

```

### What I Did

enabled fail safe mode for now

Thanks !

**Comment by pix106** [comment]
no one ?

**Comment by jamiecounsell** [comment]
Fixed in #8, appears to be related to CF downtime. Travis build is breaking, will attempt to resolve that shortly and publish to pypi

**Comment by jamiecounsell** [comment]
Resolved, sorry for the delay, @pix106. Please upgrade to v4.1.0. Please note I've dropped Python 3.4 support with v4.0.0 because of a constant battle with Travis over it, so if you're running 3.4 it will certainly still work, but is not in the official support list and so tests are not being run at that version.

**Comment by pix106** [comment]
Ok great, i will update asap.
Thanks !
